### ISSUE TITLE
Suggestion: Unify errors, make them printable, impl std Error trait

### ISSUE THREAD

**Issue by Boscop** [slowli/arithmetic-parser#12]
There seem to be like 3 different error types.
It would be great if they could all be unified so that they are all printable, and all impl `std::error::Error`.
So that they can be printed in a user-friendly way, not just using their `Debug` repr.
E.g. [`arithmetic_eval::SpannedEvalError`](https://docs.rs/arithmetic-eval/0.1.0/arithmetic_eval/struct.SpannedEvalError.html) only has the `Debug` way to print it, it has a private field `main_span` but doesn't expose it, unlike [`arithmetic_eval::ErrorWithBacktrace`](https://docs.rs/arithmetic-eval/0.1.0/arithmetic_eval/struct.ErrorWithBacktrace.html#method.main_span).

**Comment by slowli** [comment]
Makes complete sense! Initially, I've envisioned `SpannedEvalError` to be *sort of* internal, with `ErrorWithBacktrace` acting as a facade. However, in practice `SpannedEvalError` appears in too many places for this to be viable.
