### ISSUE TITLE
`'Variable is not defined'` error when calling `set_import` on `ExecutableModule` that doesn't use imported variable

### ISSUE THREAD

**Issue by Boscop** [slowli/arithmetic-parser#13]
I get the error `'Variable `x` is not defined'` when I try to call `expr.set_import("x", Value::Number(x));` on an `ExecutableModule` that I compiled with an interpreted that I had called `.insert_var("x", Value::Number(0.))` on.
This error seems to happen when the expression does not refer to the variable `x`.
I thought I could `set_import` any variable that was previously "declared as an import" via `insert_var` in the interpreter. But apparently only if the expr actually uses it :/
Presumably calling `compile` removes all unused imports (?)
IMO it should not be an error, because I would have to parse the code myself to check if the variable is used, to avoid calling `set_import`. Instead, it should silently succeed.
(In the meantime, the error msg could be improved to say "'Import `x` is not used, so it cannot be set'".)

**Comment by slowli** [comment]
> IMO it should not be an error, because I would have to parse the code myself to check if the variable is used, to avoid calling set_import. Instead, it should silently succeed.

You don't have to parse the code. `ExecutableModule` has [the `imports` getter](https://slowli.github.io/arithmetic-parser/arithmetic_eval/struct.ExecutableModule.html#method.imports), which allows to check if the import with the specified name is defined. Now, this is not optimal (a function should be added to check the existence of import without iteration - I'll do this shortly), but it works.

Regarding error messages, I don't think that silently failing (to assign an import) is the Rust way™; all errors should be as explicit and fail-fast as possible. Additionally, storing information about unused imports in the module incurs overhead without clear benefits for most of use cases. IMO, checking the import on the caller side is a better alternative.

**Comment by Boscop** [comment]
@slowli But `imports` can only be called on the compiled `ExecutableModule`. But I need to call `insert_var` for every undefined symbol that occurs in the expression (they should become imports).
So I need a way to iterate on the required imports (undefined variables) of a `Block` (so that I can call `insert_var` for each required import, before calling `compile`).

**Comment by slowli** [comment]
> So I need a way to iterate on the required imports (undefined variables) of a `Block`

This seems like a sensible feature, but I don't understand how it's related to the topic of *this* issue (calling `set_import` on an non-existing variable). Should a separate issue be created for this feature request? Sorry if I'm missing something.

Regarding how the feature request can be implemented, there's seemingly no way other than walking the AST in order to enumerate all variables and determine which ones are not defined.

**Comment by Boscop** [comment]
@slowli It's like this:
I have a set of global variables that expressions can reference. And for those that they reference, I need to call `insert_var(name, Value::Number(0.))` before compilation to avoid undefined symbols, and before each `run` of the module, I need to insert the current value of this variable by calling `set_import(name, val)`.
So if I can detect before compilation WHICH variables it references that aren't defined in the expression itself, I would only call `set_import` for those as well, so if a method like `Block::undefined_vars` was available, I would be happy and then it wouldn't matter if `set_import` gives an error when trying to set the value for an unknown variable.
