### ISSUE TITLE
Suggestion: Relaxing the lifetime of the `name` passed to `Interpreter::insert_var`

### ISSUE THREAD

**Issue by Boscop** [slowli/arithmetic-parser#14]
[`Interpreter::insert_var`](https://docs.rs/arithmetic-eval/0.1.0/arithmetic_eval/struct.Interpreter.html#method.insert_var)'s `name` arg is currently bound by the lifetime `'a`, which is the lifetime of the source code.
This means it's not possible to insert vars that are non-static (`String`s) and don't occur in the source code.

My current workaround is to scan the source code for occurrences of the variables I want to insert, to get a lifetime of the source code, and pass that to `insert_var`. But this is kind of error-prone because it doesn't take context into account, e.g. searching for `foo` inside `1+asdfoobar*2` will return a match, even though it shouldn't. (To disambiguate that, I would have to parse most of the grammar myself probably.)

```rust
pub fn parse_expr(code: String, inferred_referenced_variables: &Vec<(Variable, f32)>) -> ExprMut {
	let mut program = rentals::ExprRef::new(code, |code| {
		let mut interpreter = new_interpreter_with_prelude();

		// referenced inputs must be present for compile() to succeed
		for &(src, val) in inferred_referenced_variables {
			// can't do this because to_var_name() returns an owned String
			// interpreter.insert_var(&src.to_var_name(), Value::Number(val));

			// var_name must have code's lifetime
			let var_name = code.matches(&src.to_var_name()).next().expect("already found");
			interpreter.insert_var(var_name, Value::Number(val));
		}

		interpreter
			.compile(
				&F32Grammar::parse_statements(Span::new(code))
					.map_err(|e| format!("parsing failed: {}:{}: {}", e.line, e.offset, e.extra))
					.unwrap(),
			)
			.expect("compile")
	});

	RefCell::new(
		(box move |param_inputs| {
			program.rent_mut(|expr| {
				match expr.run() {
					Ok(ret) => {
						if let Value::Number(val) = ret {
							val
						} else {
							panic!("expected number, got: {:?}", ret);
						}
					}
					Err(e) => panic!("eval failed: {:?}", e),
				}
			})
		}) as Box<dyn ExprFn>,
	)
}
```

In this current use case, it's not a huge problem (yet) because there probably won't be cases of false matches, but I thought it still makes sense to open this issue.
Is there a way to get the list of referenced variables that need to be set (with `insert_var`) after parsing but before `compile`?
So that I could just iterate over those..

For this, it would be very useful to have a method like `Block::get_referenced_vars()` which returns an `Iterator` of `&'a str` (using the code's lifetime).
It would only return the "outer" vars it references, not those that are defined inside this `Block`. Only those that need to be inserted via `insert_var` to prevent undefined variables when compiling the expression.

**Comment by slowli** [comment]
Yeah, relaxing the lifetime makes sense not only on its own, but also to allow for further refactoring, such as enabling `'static` modules (#9).
