### ISSUE TITLE
Suggestion: Macro to generate NativeFn impls for functions of N arguments

### ISSUE THREAD

**Issue by Boscop** [slowli/arithmetic-parser#3]
It should be possible to do with a macro_rules macro, generalizing what `Binary` is doing.

**Comment by slowli** [comment]
Thanks for a suggestion! Makes complete sense to me. I can try with a solution once I get free time. Of course, if you're feeling like contributing, it would be greatly appreciated.

**Comment by Boscop** [comment]
@slowli Thanks! 
For the macro, you could take inspiration from this:
https://github.com/serde-rs/serde/blob/f3520e526b775a23a163468b6145e2b52782664d/serde/src/ser/impls.rs#L306-L346
Or this:
https://github.com/amethyst/serde-diff/blob/3825d2a6e94b7a27e5c138a500e9025e491bf8ea/src/implementation.rs#L85-L147
Or this:
https://github.com/est31/serde-big-array/blob/06193e06af1fe33b0962d13192187d16f8fc2ee4/src/lib.rs#L123-L205

Btw, am I seeing it correctly that `NativeFn`s cannot take tuples as arguments currently?

**Comment by slowli** [comment]
> Btw, am I seeing it correctly that `NativeFn`s cannot take tuples as arguments currently?

`NativeFn`s can take arguments of any type, including tuples; see [`Map`](https://github.com/slowli/arithmetic-parser/blob/f653e5ec45dcb6147356e5f2f4cb0233a9fa27b5/eval/src/fns.rs#L302) or [`Fold`](https://github.com/slowli/arithmetic-parser/blob/f653e5ec45dcb6147356e5f2f4cb0233a9fa27b5/eval/src/fns.rs#L433) for examples. Wrappers like `Unary` or `Binary` indeed take only primitive arguments as of now. I suppose it would be easy to implement their variants supporting per-element recursion for tuples, something like `max((1, 2), (-3, 4)) == (1, 4)`.

Btw, now that I think about it, "tuple" may be a slightly misleading term; like in JavaScript, tuples and arrays share a single container type.

**Comment by Boscop** [comment]
Yeah, since elements can be pushed to tuples, they are more like arrays, not static types..
I think it would make sense to merge the two names and only have arrays in the language (but with destructuring).

**Comment by slowli** [comment]
@Boscop I've sketched extended support of native functions in #5. Does it correspond to your expectations in broad terms? The error handling is not completed so far; I want to return detailed info where the argument conversion has failed (something like "2nd argument: 1st element of an array: expected a 2-element tuple, but got a number").

**Comment by Boscop** [comment]
Sorry I haven't had time to apply this to my use case yet. I'll apply it soon.
My use case is: Configurable automation for parameters over time.

**Comment by Boscop** [comment]
@slowli Btw, in my use case I need to evaluate a program to an owned expression (`'static`), cache it and evaluate it later on many times (the expr is a function, basically f32 -> f32). 
I'm running into an issue: 
It seems there is no way to make the expr owned (`'static`)? (E.g. via `.to_owned()`)?

EDIT: Since that is unrelated to this, I opened a new issue: https://github.com/slowli/arithmetic-parser/issues/9

**Comment by Boscop** [comment]
I have been using this branch. Thanks for the improvements, the `wrap` function is very useful, but I think ergonomics can be improved more, to allow better type inference, e.g. like this: https://github.com/slowli/arithmetic-parser/issues/8#issuecomment-653782175
