### ISSUE TITLE
Owned version of `ExecutableModule`

### ISSUE THREAD

**Issue by Boscop** [slowli/arithmetic-parser#9]
In my use case I need to evaluate a program to an owned expression (`'static`), cache it and evaluate it later on many times (the expr is a function, basically f32 -> f32). 
It seems there is no way to make the expr owned (`'static`)? (E.g. via `.to_owned()`)?
I found a way to do it with the `rental` crate:
```rust
rental! {
	mod rentals {
		use super::*;

		#[rental_mut]
		pub struct ExprRef {
			code: String,
			expr: ExecutableModule<'code, F32Grammar>,
		}
	}
}
```
and then:
```rust
let make_func = |code| {
	let mut program = rentals::ExprRef::new(code, |code| {
		new_interpreter_with_prelude()
			.compile(&F32Grammar::parse_statements(Span::new(code)).unwrap())
			.unwrap()
	});

	(box move |x| {
		program.rent_mut(|expr| {
			expr.set_import("x", Value::Number(x));
			match expr.run() {
				Ok(ret) => {
					if let Value::Number(val) = ret {
						val
					} else {
						panic!("expected number, got: {:?}", ret);
					}
				}
				Err(e) => panic!("eval failed: {}", e.source()),
			}
		})
	}) as Box<dyn FnMut(f32) -> f32>
}
```
But it would be nice if it didn't require rental, just calling `.to_owned()` on it.

Btw, notice that I have to use `#[rental_mut]` and `program.rent_mut()`, I wish this wasn't necessary: https://github.com/slowli/arithmetic-parser/issues/7

**Comment by slowli** [comment]
Thanks for the suggestion! As you've pointed out, the lifetime dependency is indeed associated with the spans in the source code, which are mostly used for error generation. If the spans are collapsed (e.g., so that the locations are retained but the code itself is collapsed into `""`), then it seems doable to assign `'static` lifetime for the module.
